#!/bin/bash

##################################################################################################################################################################################################################################################################################

#Function: Filters all cluster files.

#Concept: #After detecting clustered mutations in the pairwise alignments, filter out clusters that couldn’t be strongly associated with APOBEC-mediated DNA editing and may be generated by the accumulation of random mutations.

	  #2 Major filters applied are:
		#1. Pairwise filter:
			#Min. # mismatch per alignment(one or more clusters)            : 10
			#Percent of mismatch and reverse (e.g. GA / (GA + AG) * 100)    : 60
			#Percent of mismatch and complement (e.g. GA / (GA + CT) * 100) : 60
			#Percent of all mismatches in alignment                         : 33.333
			#Minimal span of clusters (bps)                                 : 60
		#2. Consensus filter:
			#Edited element containing A has more divergence score than the correspoding repbase consensus sequence containing G.
			#Positions containing G>A mutations in the edited element align to guanosines in the consensus more often than to adenosines.

	  #More info about the steps is explained in the script getFilteredClusterFile.pl

#Input:
	#Unflitered cluster files located inside `Tracks/tracks*` folder.
	#Mapped data of edited element to the closest repbase consensus named: nucListFreqPerPair.*.txt.
	#Script used: getFilteredClusterFile.pl

##################################################################################################################################################################################################################################################################################

#Usage: ./knisbacher_script_step_4_Filter_clusters.sh mm

#Options:
        #1. family (Repeat type): available options are: LTR, DNA, LINE, SINE
        #2. mm (mismatch type) : available options are: GA, CT

#Example runs:
        #nohup ./knisbacher_script_step_4_Filter_clusters.sh LTR GA &
        #nohup ./knisbacher_script_step_4_Filter_clusters.sh DNA GA &
        #nohup ./knisbacher_script_step_4_Filter_clusters.sh LTR CT &

##################################################################################################################################################################################################################################################################################

#Set path variables
base_dir="/media/aswin/gene_loss/APOBEC1/hypermutation_analyses/identify_retrotransposons/"
script_dir="/media/aswin/gene_loss/APOBEC1/hypermutation_analyses/identify_retrotransposons/scripts/Perl_DNAE"

#Root directory
cd $base_dir

#Set perl version
perlbrew use perl-5.16.3 &> /dev/null

#Project
echo -e "\nESTIMATE APOBEC INDUCED DNA EDITED SITES IN AVIAN LTR RETROTRANSPOSONS\n\n - Filter $2 clusters in $1:\n" > stdout_knisbacher_script_step_4_Filter_clusters_of_"$1"_"$2"_81_birds

###########################################################################################################################################################################################################################################$

#Run getFilteredClusterFile.pl for all raw clusters given the folder `Tracks` exists.
{
  time while read -r i
  do
  o=$(echo $i | awk -F "_" '{print substr($1,1,3)""substr($2,1,3)}')
  cd $i/knisbacher
  echo ">"$i "(" $o ")"
  echo -e "\nESTIMATE APOBEC INDUCED DNA EDITED SITES IN AVIAN LTR RETROTRANSPOSONS\n\n - Filter $2 clusters in $1:\n" > stdout_knisbacher_script_step_4_Filter_clusters_of_"$1"_"$2"
  echo -e "  - Run getFilteredClusterFile.pl..." >> stdout_knisbacher_script_step_4_Filter_clusters_of_"$1"_"$2"

  #Filter clusters
  {
  if [[ -d Data/"$o"/"$1"/results/Tracks ]]
    then
    echo "   - Folder named Tracks found:"
    for cluster in $(find Data/"$o"/"$1"/results/Tracks/ -maxdepth 4 -mindepth 3 -path "*/$2/raw/*" -name "clusters_*.tab")
      do
      echo "    - "$cluster
      time perl $script_dir/analysis_scripts/getFilteredClusterFile.pl $2 $cluster "$o"_RepeatMasker.out
    done
    else
    echo "   - Folder named Tracks no found!"
  fi
    } &>> stdout_knisbacher_script_step_4_Filter_clusters_of_"$1"_"$2"

  unset o family
  cd $base_dir
  done < all_bird_genomes_used
} &>> stdout_knisbacher_script_step_4_Filter_clusters_of_"$1"_"$2"_81_birds


#END#
###########################################################################################################################################################################################################################################$
